# Generated by Django 5.1.7 on 2025-03-20 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.branch')),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('loan_code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=17)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.accounttype')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expiry_date', models.DateField()),
                ('card_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer'),
        ),
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('support_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('tenure', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Approved', 'APPROVED'), ('Pending', 'PENDING'), ('Repaid', 'REPAID'), ('Overdue', 'OVERDUE')], default='Pending', max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.employee')),
                ('loan_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Paid', 'PAID'), ('Overdue', 'OVERDUE')], default='Pending', max_length=20)),
                ('payment_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('manager_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.employee')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.branch')),
            ],
        ),
    ]
