# Generated by Django 5.1.7 on 2025-03-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transactionType', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Successful', 'Successful'), ('Pending', 'Pending')], max_length=20)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.employee')),
                ('receiver_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_transactions', to='bank.account')),
            ],
        ),
    ]
