# Generated by Django 5.1.7 on 2025-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='cust1', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='customer1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
